x-common: &common-setup
  network_mode: host
  privileged: true
  stdin_open: true
  tty: true
  image: fabook/iros:v0.0.3
  working_dir: /home/fabian/ros2_ws
  volumes:
    - ${HOME}/.Xauthority:/home/fabian/.Xauthority:rw
    - .:/home/fabian/ros2_ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri:rw
    - /run/user/1000/pulse:/run/user/1000/pulse
    - /dev/v4l:/dev/v4l:ro
  devices:
    - /dev/video0:/dev/video0
    - /dev/video1:/dev/video1
    - /dev/snd:/dev/snd
  group_add:
    - "video"
    - "44"
  environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1
    - PULSE_SERVER=unix:/run/user/1000/pulse/native
    # DDS
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - ROS_DOMAIN_ID=42
    - CYCLONEDDS_URI=file:///home/fabian/ros2_ws/src/scripts/cyclonedds_swarm.xml
  command: ["/bin/bash", "-lc", "exec bash"]

services:
  # С GPU (CUDA / PyTorch)
  terminal:
    <<: *common-setup
    container_name: iros_terminal_gpu
    gpus: all
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=42
      - CYCLONEDDS_URI=file:///home/fabian/ros2_ws/src/scripts/cyclonedds_swarm.xml
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video,graphics,display

  # Без GPU (CPU-only, для отладки на машинах без NVIDIA)
  terminal-cpu:
    <<: *common-setup
    container_name: iros_terminal_cpu